"""Generate the single current notebook from the maintained source cells."""
from pathlib import Path
import json
import nbformat as nbf
PROJECT=Path(__file__).resolve().parents[1]
CELL_SOURCES=json.loads(r'''[
  {
    "cell_type": "markdown",
    "source": "# ME2 - VCM on Raspberry Pi 5: training and evaluation\n\nThis notebook documents the **ME2 Spoken Command Dataset** and the two scratch-trained TinyDSCNN-48 models: binary wake detection and 31-class intent classification. It reads the active pair and saved evaluation. Set `RETRAIN = True` to launch a new scratch run with live epoch output; the training script then stages, packages and synchronizes the completed pair to the Pi by default. Opening the notebook never trains or deploys because `RETRAIN` defaults to `False`.\n\n**Evidence boundary:** the reference test is reused, and personal clips share speakers across partitions. The active release is read from metadata; wake-only refreshes explicitly retain the prior intent weights. Several intent classes still fail the 95% goal. Fixed wake operating threshold 0.95 and validation-selected threshold are reported separately. Live speech testing remains distinct from saved-WAV replay."
  },
  {
    "cell_type": "code",
    "source": "from pathlib import Path\nimport hashlib, json, subprocess, sys\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom IPython.display import display, Image\n\nROOT = next((p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents) if (p / 'tinyvcm/config.py').is_file()), None)\nif ROOT is None: raise RuntimeError('Run the notebook from the ME2 project folder.')\nSTAGED = ROOT / 'deployment/current_vcm'\nMETA = json.loads((STAGED / 'metadata.json').read_text(encoding='utf-8'))\nSTAGED_RUN = ROOT / 'runs' / META['source_run']\nRUN = STAGED_RUN\nREPORT = json.loads((RUN / 'final_evaluation.json').read_text(encoding='utf-8'))\nprint('Shared interpreter:', sys.executable)\nprint('Dataset:', META['dataset_name'])\nprint('Active evaluation run:', RUN)\nprint('Currently staged run:', STAGED_RUN)\nprint('Staged wake operating threshold:', META['wake']['local_operating_threshold'])\n"
  },
  {
    "cell_type": "markdown",
    "source": "## Dataset and label audit\n\nThe machine-readable alignment check compares the training manifest, all 31 recorder choices, every ground-truth phrase file, and the ten course command groups. Existing unsupported legacy slot values are not silently relabeled.\n"
  },
  {
    "cell_type": "code",
    "source": "alignment = json.loads((ROOT / 'docs/ME2_DATASET_ALIGNMENT.json').read_text(encoding='utf-8'))\nassert alignment['recorder_intent_labels_match'] and alignment['manifest_labels_match']\nassert not alignment['suggested_phrase_not_in_training_transcripts']\nassert alignment['staged_intent_labels_match']\ndisplay(pd.DataFrame([{\n    'reference dataset clips': alignment['dataset_rows'], 'reference speakers': alignment['dataset_speakers'],\n    'personal saved takes': alignment['human_manifest_rows'],\n    'personal classes missing': len(alignment['intent_classes_with_no_personal_rows']),\n    'exact recorder prompts': len(META['intent']['classes']),\n    'historical prompts recoverable': 0\n}]))\ndisplay(pd.DataFrame([{'course group': k, 'classes': ', '.join(v)} for k,v in alignment['course_command_groups'].items()]))\n"
  },
  {
    "cell_type": "markdown",
    "source": "## Architecture\n\nBoth models share the same four depthwise-separable blocks and 48-channel topology. Only the final dense head changes: 2 wake logits or 31 intent logits. NetworkX diagrams were generated by executing the PyTorch model and recording output shapes and parameter counts."
  },
  {
    "cell_type": "code",
    "source": "architecture = json.loads((ROOT / 'docs/ME2_ARCHITECTURE_VERIFIED.json').read_text(encoding='utf-8'))\ndisplay(pd.DataFrame(architecture['intent_stages'], columns=['stage','output shape','parameters']))\nprint('Wake parameters:', architecture['wake_parameters'], 'Intent parameters:', architecture['intent_parameters'])\ndisplay(Image(filename=str(ROOT / 'docs/ME2_TinyDSCNN48_connections_preview.png')))\n"
  },
  {
    "cell_type": "markdown",
    "source": "## Reproduce from random initialization\n\nSet `RETRAIN = True` for a new scratch run. Epoch progress prints live. On completion the script updates `deployment/current_vcm/`, prepares the package and syncs it to the Pi; use `--train-only` only to explicitly skip deployment. If the Pi is offline the package is pending and training exits with deployment status code 3. The Desktop launcher retries sync when the Pi reconnects. Keep a fresh speaker completely held out for generalization tests."
  },
  {
    "cell_type": "code",
    "source": "RETRAIN = False\nWAKE_ONLY = False  # True only when no new intent clips have been added\nif RETRAIN:\n    stamp = pd.Timestamp.now().strftime('%Y%m%d-%H%M%S')\n    run_name = f'me2-vcm-notebook-{stamp}'\n    command = [sys.executable, '-u', str(ROOT / 'scripts/train_me2_vcm.py'),\n               '--run-name', run_name]\n    if WAKE_ONLY: command.append('--wake-only')\n    print('Starting a new scratch run:', ' '.join(command), flush=True)\n    subprocess.run(command, cwd=ROOT, check=True)\n    META = json.loads((STAGED / 'metadata.json').read_text(encoding='utf-8'))\n    RUN = ROOT / 'runs' / run_name\n    REPORT = json.loads((RUN / 'final_evaluation.json').read_text(encoding='utf-8'))\nelse:\n    print('Using the saved active evaluation. Set RETRAIN=True for another scratch run.')\nintent_report = REPORT['intent_model_comparison']['personalized_int8']\nreference_report = intent_report['optionb_test']\npersonal_report = intent_report['personal_heldout_test']\nprint('Active run:', RUN)\nprint(f\"Reference test accuracy: {reference_report['accuracy']:.4%}\")\nprint(f\"Personal clip-holdout accuracy: {personal_report['accuracy']:.4%} (n={personal_report['count']})\")\n"
  },
  {
    "cell_type": "markdown",
    "source": "## Saved epoch progress and checkpoint selection\n\nThese histories belong to the selected evaluation candidate above. Checkpoint selection uses validation scores. The wake threshold selected by validation and the fixed 0.95 staged operating cutoff are reported separately; do not treat either as an accuracy percentage.\n\nThe manifest snapshot freezes the corpus before training. For wake-only runs, the intent history belongs to the retained source run printed below.\n"
  },
  {
    "cell_type": "code",
    "source": "print('Pair provenance:', META.get('pair_provenance', {'note':'full scratch pair'}))\nwake_history = pd.DataFrame(json.loads((RUN / 'wake_binary/history.json').read_text(encoding='utf-8'))['history'])\nintent_history = pd.DataFrame(json.loads((RUN / 'intent_personalized/history.json').read_text(encoding='utf-8'))['history'])\nmacro_col = next(c for c in intent_history if c.startswith('val_') and c.endswith('_macro_f1') and 'personal' not in c)\nminimum_col = next(c for c in intent_history if c.endswith('_min_class_f1'))\nintent_history = intent_history.rename(columns={macro_col:'val_reference_macro_f1',minimum_col:'val_reference_min_class_f1'})\ndisplay(wake_history[['epoch','train_loss','val_zero_FA_wake_recall','val_threshold']])\nintent_columns = [c for c in ('epoch','train_loss','val_reference_macro_f1','val_reference_min_class_f1','val_personal_macro_f1','checkpoint_score') if c in intent_history]\ndisplay(intent_history[intent_columns])\nfig, axes = plt.subplots(1,2,figsize=(12,4))\naxes[0].plot(wake_history.epoch, wake_history.val_zero_FA_wake_recall); axes[0].set(title='Wake validation recall at zero false accepts',xlabel='Epoch',ylabel='Recall',ylim=(0,1.02))\naxes[1].plot(intent_history.epoch, intent_history.val_reference_macro_f1,label='Reference macro F1');\nif 'val_reference_min_class_f1' in intent_history: axes[1].plot(intent_history.epoch,intent_history.val_reference_min_class_f1,label='Weakest class F1')\naxes[1].set(title='Intent validation',xlabel='Epoch',ylabel='F1',ylim=(0,1.02)); axes[1].legend(); plt.tight_layout(); display(fig); plt.close(fig)\n"
  },
  {
    "cell_type": "markdown",
    "source": "## Frozen INT8 evaluation and operating threshold\n\nThe tables show the active pair's reference and personal scores. No test results are used to tune a threshold here. The Pi uses the fixed 0.95 wake cutoff. The near-one validation cutoff remains in the historical evaluation as a separate measurement; neither score establishes false wake activations per hour."
  },
  {
    "cell_type": "code",
    "source": "candidate_wake = REPORT['wake_model_comparison']['binary']\ncandidate_intent = REPORT['intent_model_comparison']['personalized_int8']\nreference = candidate_intent['optionb_test']\npersonal = candidate_intent['personal_heldout_test']\nwake_table = pd.DataFrame([{\n    'candidate validation threshold': candidate_wake['validation_selected_int8_threshold'],\n    'held-out personal wake hits': f\"{candidate_wake['heldout_personal_wake_hits']}/{candidate_wake['heldout_personal_wake_support']}\",\n    'false accepts / reference commands': f\"{candidate_wake['false_wake_on_optionb_command_clips']}/{candidate_wake['optionb_command_support']}\",\n    'false accepts / personal non-wake': f\"{candidate_wake['false_wake_on_personal_nonwake_clips']}/{candidate_wake['personal_nonwake_support']}\"\n}])\ndisplay(wake_table)\ndisplay(pd.DataFrame([{\n    'reference accuracy': reference['accuracy'],\n    'reference macro F1': reference['classification_report']['macro avg']['f1-score'],\n    'personal accuracy': personal['accuracy'],\n    'personal macro F1': personal['classification_report']['macro avg']['f1-score'],\n    'personal test clips': personal['count']\n}]))\nclasses = pd.DataFrame([{'class': label, **row} for label,row in reference['classification_report'].items()\n                        if label not in ('accuracy','macro avg','weighted avg')])\nclasses = classes.rename(columns={'f1-score':'f1'})\nclasses['meets 95% precision, recall and F1'] = (classes['precision'] >= .95) & (classes['recall'] >= .95) & (classes['f1'] >= .95)\ndisplay(classes)\nprint('Reference classes below 95% F1:', classes.loc[classes['f1'] < .95,'class'].tolist())\nprint('Offline intent metrics: argmax. Live acceptance: confidence >= 0.68 and top-two margin >= 0.15 for all classes.')\n\npoint = META['wake']['operating_point_replay']\ndisplay(pd.DataFrame([{'deployed wake threshold':point['threshold'],\n    'wake hits':f\"{point['personal_wake_hits']}/{point['personal_wake_support']}\",\n    'personal false accepts':f\"{point['personal_nonwake_false_accepts']}/{point['personal_nonwake_support']}\",\n    'reference false accepts':f\"{point['dataset_command_false_accepts']}/{point['dataset_command_support']}\"}]))\n"
  },
  {
    "cell_type": "code",
    "source": "for kind in ('wake','intent'):\n    model = META[kind]['model']\n    path = STAGED / model['path']\n    actual = hashlib.sha256(path.read_bytes()).hexdigest()\n    assert actual == model['sha256']\n    print('active', kind, path.name, path.stat().st_size, 'bytes', actual)\nprint('Combined ONNX size:', sum(META[k]['model']['size_bytes'] for k in ('wake','intent')), 'bytes')\nlatest = json.loads((ROOT / 'deployment/latest_release.json').read_text(encoding='utf-8'))\nreceipt = json.loads((ROOT / 'deployment/last_pi_deployment.json').read_text(encoding='utf-8'))\nprint('Last synchronization status:', latest['status'], latest['source_run'])\nprint('Verified Pi path:', receipt['installed_at'])\nprint('Pi CPU benchmark:', receipt['verification']['model_results'])\nprint('These files record the last deployment check. Consult the live API before a new hardware trial.')\n"
  }
]''')
def main():
    nb=nbf.v4.new_notebook()
    nb.metadata={'kernelspec':{'display_name':'Python (AI 222 + AI 231)','language':'python','name':'ai222-231'},'language_info':{'name':'python','version':'3.12'}}
    nb.cells=[nbf.v4.new_code_cell(c['source']) if c['cell_type']=='code' else nbf.v4.new_markdown_cell(c['source']) for c in CELL_SOURCES]
    target=PROJECT/'notebooks/ME2_Tiny_VCM_Training.ipynb'
    nbf.write(nb,target)
    print(target)
if __name__=='__main__':main()
