"""Build and execute the ME2_Wake2_Binary.ipynb notebook cleanly in the shared environment."""
import json
from pathlib import Path
import sys
import time

import nbformat
from nbclient import NotebookClient

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = PROJECT_ROOT / 'notebooks' / 'ME2_Wake2_Binary.ipynb'

CELLS = [
    # Cell 0: Header & Academic Declarations
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# AI 231 MEX2: Embedded Voice Command System\n",
            "## Task D: Dedicated Two-Class Binary Wake-Word Detector (`NON_WAKE` vs `WAKE_WORD`)\n",
            "\n",
            "**Student**: Crizepvill F. Dumalaog (SN: 202521406)  \n",
            "**Course**: AI 231 (Deep Learning Systems) — Machine Exercise 2  \n",
            "**Model Architecture**: `TinyDSCNN-Binary` (Stem + 4 Depthwise-Separable Blocks + Linear(48 -> 2))  \n",
            "**Total Parameters**: 13,106 parameters (~55.0 KB FP32 / ~36.8 KB Static INT8 ONNX)  \n",
            "**Execution Date**: 2026-09-28 (Asia/Manila)  \n",
            "**Status**: Experimental two-stage edge candidate for independent Codex audit prior to deployment.\n",
            "\n",
            "---\n",
            "\n",
            "### Architectural Rationale: Why Decoupled Binary Detection?\n",
            "1. **Root Cause of Single-Model 32-Class Failure**: In the installed 32-class model, `WAKE_WORD` competes against 31 command intents in a single softmax layer with a hardcoded `conf >= 0.60` top-1 gate. An independent diagnostic on 16 unique saved wake recordings from the user's voice showed that **only 8 reached 0.60** when evaluated in offline windows.\n",
            "2. **Two-Stage Decoupled Pipeline**:\n",
            "   - **Stage 1 (This Model)**: Dedicated lightweight binary gatekeeper (`NON_WAKE` vs `WAKE_WORD`). Evaluates streaming audio continuously with temporal rolling invariance and dedicated threshold $\\theta^*$.\n",
            "   - **Stage 2 (Course Option B Model)**: 31-class command classifier (`vcm_optionb_int8.onnx`, 96.27% accuracy, 14,527 parameters). Activated only during the 10-second post-wake listening window.\n",
            "3. **Streaming Invariance via Temporal Rolling**: In streaming buffers, speech rarely arrives dead-center. The binary training pipeline injects random temporal rolling (0.0s to 1.5s offset) so the model recognizes `\"Hi Dandan\"` whether it appears at the start, center, or trailing edge of the 2.5-second buffer.\n",
            "4. **Strict Partitioning & Calibration Provenance**:\n",
            "   - **Human Wake**: 18 rows deduplicated into 16 unique decoded PCM waveforms. Split into 10 train (with repeated rows grouped), 3 validation (2 near + 1 far), and 3 test (2 near + 1 far).\n",
            "   - **Synthetic Wake**: 315 files partitioned 7 / 1 / 1 by source prompt ID.\n",
            "   - **Option B Negatives**: Preserves strict 80 / 10 / 10 disjoint speaker partitions.\n",
            "   - **INT8 Calibration**: Exactly 256 training-only stratified samples (128 positive, 128 negative). Zero validation or test samples touched during quantization.\n",
            "   - **Threshold Selection**: Operating threshold $\\theta^*$ selected purely from validation tradeoff (prioritizing 100% human wake recall and zero command false alarms).\n"
        ]
    },
    # Cell 1: Setup & System Verification
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import os\n",
            "import sys\n",
            "from pathlib import Path\n",
            "import time\n",
            "import json\n",
            "import hashlib\n",
            "import numpy as np\n",
            "import torch\n",
            "import onnx\n",
            "import onnxruntime as ort\n",
            "\n",
            "# Workspace resolution\n",
            "PROJECT_ROOT = Path.cwd()\n",
            "if PROJECT_ROOT.name != 'Dumalaog_ME2 - Tiny Voice Command Model':\n",
            "    PROJECT_ROOT = PROJECT_ROOT / 'AI 231' / 'Dumalaog_ME2 - Tiny Voice Command Model'\n",
            "if str(PROJECT_ROOT) not in sys.path:\n",
            "    sys.path.insert(0, str(PROJECT_ROOT))\n",
            "\n",
            "print(f\"Project Root:  {PROJECT_ROOT}\")\n",
            "print(f\"Python:        {sys.version.split()[0]}\")\n",
            "print(f\"PyTorch:       {torch.__version__} (CUDA: {torch.cuda.is_available()})\")\n",
            "if torch.cuda.is_available():\n",
            "    print(f\"GPU:           {torch.cuda.get_device_name(0)}\")\n",
            "print(f\"ONNX Runtime:  {ort.__version__}\")\n",
            "print(f\"Binary Labels: ['NON_WAKE', 'WAKE_WORD']\")\n"
        ]
    },
    # Cell 2: Dataset Loading, Grouping & Temporal Jitter Preparation
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from tinyvcm_model.binary_dataset import prepare_binary_data\n",
            "\n",
            "SEED = 231\n",
            "print(\"Loading datasets and generating streaming jitter augmentations (seed=231)...\")\n",
            "t0 = time.time()\n",
            "data = prepare_binary_data(PROJECT_ROOT, rng_seed=SEED)\n",
            "splits = data['splits_info']\n",
            "\n",
            "print(f\"Data preparation complete in {time.time()-t0:.2f}s.\")\n",
            "print(f\"\\n--- Training Partition ---\")\n",
            "print(f\"Total Training Samples: {splits['train_samples']:,}\")\n",
            "print(f\"  - Positive Wake Samples: {splits['train_positives']:,} (10 human wake waveforms x 75 jittered + 245 synth x 2)\")\n",
            "print(f\"  - Negative Non-Wake Samples: {splits['train_negatives']:,} (Option B commands + noise)\")\n",
            "print(f\"\\n--- Validation Partition ---\")\n",
            "print(f\"Total Validation Samples: {splits['val_samples']:,}\")\n",
            "print(f\"  - Positive Wake Samples: {splits['val_positives']} (3 held-out human wake groups [2 near + 1 far] + 35 synth)\")\n",
            "print(f\"  - Negative Non-Wake Samples: {splits['val_negatives']:,} (1,818 Option B val clips)\")\n",
            "print(f\"\\n--- Held-Out Test Partition (Frozen & Unopened) ---\")\n",
            "print(f\"  - Human Wake Test Groups: {splits['test_hw_groups']} groups (2 near + 1 far)\")\n",
            "print(f\"  - Synthetic Wake Test: {splits['test_synth_groups']} group (35 files)\")\n",
            "print(f\"  - Option B Command Test: {len(data['optb_test_x']):,} clips across 10 unseen speakers\")\n",
            "print(f\"\\n--- Calibration Partition (Training-Only) ---\")\n",
            "print(f\"  - Stratified INT8 Samples: {splits['calib_samples']} (128 wake + 128 non-wake, 0 val/test)\")\n"
        ]
    },
    # Cell 3: Model Initialization & Provable Hash Locking
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from tinyvcm_model.model import TinyDSCNN\n",
            "from tinyvcm_model.binary_trainer import compute_model_param_hash\n",
            "\n",
            "torch.manual_seed(SEED)\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.manual_seed_all(SEED)\n",
            "\n",
            "model = TinyDSCNN(classes=2, channels=48, dropout=0.15)\n",
            "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
            "model.to(device)\n",
            "\n",
            "total_params = sum(p.numel() for p in model.parameters())\n",
            "initial_weights_hash = compute_model_param_hash(model)\n",
            "\n",
            "print(\"=\" * 75)\n",
            "print(\"  TINYDSCNN-BINARY MODEL INITIALIZATION PROVENANCE\")\n",
            "print(\"=\" * 75)\n",
            "print(f\"Random Initialization Seed: {SEED}\")\n",
            "print(f\"Pretrained Weights Used:    False (strict random scratch initialization)\")\n",
            "print(f\"Total Model Parameters:     {total_params:,}\")\n",
            "print(f\"Initial Weights SHA-256:    {initial_weights_hash}\")\n",
            "print(f\"Architecture Breakdown:\")\n",
            "print(f\"  - Conv2D Stem:             1,296 params (1 -> 48 ch, 5x5, stride (2,2), BN, ReLU)\")\n",
            "print(f\"  - 4 DS Blocks:             11,712 params (4 x 2,928 params)\")\n",
            "print(f\"  - Linear Head:             98 params (48 -> 2 logits + bias)\")\n",
            "print(\"=\" * 75)\n"
        ]
    },
    # Cell 4: 35-Epoch Training Loop with Visible Progress
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import copy\n",
            "from torch.utils.data import DataLoader\n",
            "from tinyvcm_model.binary_dataset import BinaryWakeDataset\n",
            "from tinyvcm_model.frontend import Frontend, fit_audio\n",
            "from tinyvcm_model.config import SAMPLES\n",
            "import soundfile as sf\n",
            "\n",
            "EPOCHS = 35\n",
            "BATCH_SIZE = 64\n",
            "LR = 3e-3\n",
            "\n",
            "train_ds = BinaryWakeDataset(data['train_x'], data['train_y'], augment=True, rng_seed=SEED)\n",
            "val_ds = BinaryWakeDataset(data['val_x'], data['val_y'], augment=False, rng_seed=SEED)\n",
            "\n",
            "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)\n",
            "val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
            "\n",
            "w_neg = 1.0\n",
            "w_pos = float(splits['train_negatives']) / float(splits['train_positives'])\n",
            "class_weights = torch.tensor([w_neg, w_pos], dtype=torch.float32, device=device)\n",
            "criterion = torch.nn.CrossEntropyLoss(weight=class_weights)\n",
            "optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
            "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=3e-5)\n",
            "\n",
            "frontend = Frontend()\n",
            "history = []\n",
            "best_val_score = -1.0\n",
            "best_epoch = -1\n",
            "best_weights = None\n",
            "\n",
            "print(f\"Starting {EPOCHS}-epoch training loop on {device}...\")\n",
            "for epoch in range(1, EPOCHS + 1):\n",
            "    t_start = time.time()\n",
            "    model.train()\n",
            "    train_loss = 0.0\n",
            "    train_correct = 0\n",
            "    train_total = 0\n",
            "\n",
            "    for bx, by in train_loader:\n",
            "        bx, by = bx.to(device), by.to(device)\n",
            "        optimizer.zero_grad()\n",
            "        logits = model(bx)\n",
            "        loss = criterion(logits, by)\n",
            "        loss.backward()\n",
            "        optimizer.step()\n",
            "\n",
            "        train_loss += loss.item() * len(by)\n",
            "        preds = logits.argmax(dim=-1)\n",
            "        train_correct += (preds == by).sum().item()\n",
            "        train_total += len(by)\n",
            "\n",
            "    scheduler.step()\n",
            "    train_loss /= train_total\n",
            "    train_acc = train_correct / train_total\n",
            "\n",
            "    # Validation evaluation\n",
            "    model.eval()\n",
            "    val_loss = 0.0\n",
            "    all_val_probs = []\n",
            "    all_val_targets = []\n",
            "\n",
            "    with torch.no_grad():\n",
            "        for bx, by in val_loader:\n",
            "            bx, by = bx.to(device), by.to(device)\n",
            "            logits = model(bx)\n",
            "            loss = criterion(logits, by)\n",
            "            val_loss += loss.item() * len(by)\n",
            "            probs = torch.softmax(logits, dim=-1)[:, 1]\n",
            "            all_val_probs.extend(probs.cpu().numpy().tolist())\n",
            "            all_val_targets.extend(by.cpu().numpy().tolist())\n",
            "\n",
            "    val_loss /= len(all_val_targets)\n",
            "    val_probs_arr = np.array(all_val_probs)\n",
            "    val_targets_arr = np.array(all_val_targets)\n",
            "    neg_probs = val_probs_arr[val_targets_arr == 0]\n",
            "\n",
            "    # Human wake recall on validation takes\n",
            "    val_hw_probs = []\n",
            "    for it in data['val_hw_items']:\n",
            "        spec = frontend(fit_audio(it['wav'], target_samples=SAMPLES))\n",
            "        with torch.no_grad():\n",
            "            inp = torch.from_numpy(spec[None, ...]).float().to(device)\n",
            "            val_hw_probs.append(torch.softmax(model(inp), dim=-1)[0, 1].item())\n",
            "    val_hw_recall = float(np.mean([1.0 if p >= 0.50 else 0.0 for p in val_hw_probs]))\n",
            "\n",
            "    # Synthetic wake recall\n",
            "    val_synth_probs = []\n",
            "    for sf_path in data['val_synth_files']:\n",
            "        sw, _ = sf.read(str(sf_path), dtype='float32')\n",
            "        if sw.ndim > 1:\n",
            "            sw = sw.mean(axis=1)\n",
            "        spec = frontend(fit_audio(sw, target_samples=SAMPLES))\n",
            "        with torch.no_grad():\n",
            "            inp = torch.from_numpy(spec[None, ...]).float().to(device)\n",
            "            val_synth_probs.append(torch.softmax(model(inp), dim=-1)[0, 1].item())\n",
            "    val_synth_recall = float(np.mean([1.0 if p >= 0.50 else 0.0 for p in val_synth_probs]))\n",
            "\n",
            "    false_alarms = int((neg_probs >= 0.50).sum())\n",
            "    fa_rate = false_alarms / len(neg_probs)\n",
            "    val_score = (val_hw_recall * 0.45) + ((1.0 - fa_rate) * 0.45) + (val_synth_recall * 0.10)\n",
            "\n",
            "    epoch_time = time.time() - t_start\n",
            "    is_best = val_score > best_val_score\n",
            "    if is_best:\n",
            "        best_val_score = val_score\n",
            "        best_epoch = epoch\n",
            "        best_weights = copy.deepcopy(model.state_dict())\n",
            "\n",
            "    marker = \" [BEST]\" if is_best else \"\"\n",
            "    print(f\"Epoch {epoch:2d}/{EPOCHS:2d} ({epoch_time:4.1f}s) | Train Loss: {train_loss:.4f} Acc: {train_acc*100:5.2f}% | \"\n",
            "          f\"Val Score: {val_score:.4f} HW Rec: {val_hw_recall*100:5.1f}% FA: {false_alarms}/{len(neg_probs)} ({fa_rate*100:4.2f}%){marker}\")\n",
            "\n",
            "model.load_state_dict(best_weights)\n",
            "RUN_DIR = PROJECT_ROOT / f'runs/vcm-wake2-binary-{time.strftime(\"%Y%m%d-%H%M%S\")}'\n",
            "RUN_DIR.mkdir(parents=True, exist_ok=True)\n",
            "(RUN_DIR / 'models').mkdir(parents=True, exist_ok=True)\n",
            "torch.save(best_weights, RUN_DIR / 'best_model.pt')\n",
            "print(f\"\\nBest checkpoint from Epoch {best_epoch} (Score: {best_val_score:.4f}) saved to {RUN_DIR.name}.\")\n"
        ]
    },
    # Cell 5: Validation Operating Threshold Sweep & Selection
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "model.eval()\n",
            "thresholds = [round(t, 2) for t in np.arange(0.10, 0.95, 0.05)]\n",
            "\n",
            "# Final validation positive & negative distributions\n",
            "val_hw_probs_final = []\n",
            "for it in data['val_hw_items']:\n",
            "    spec = frontend(fit_audio(it['wav'], target_samples=SAMPLES))\n",
            "    with torch.no_grad():\n",
            "        inp = torch.from_numpy(spec[None, ...]).float().to(device)\n",
            "        val_hw_probs_final.append(torch.softmax(model(inp), dim=-1)[0, 1].item())\n",
            "\n",
            "val_synth_probs_final = []\n",
            "for sf_path in data['val_synth_files']:\n",
            "    sw, _ = sf.read(str(sf_path), dtype='float32')\n",
            "    if sw.ndim > 1:\n",
            "        sw = sw.mean(axis=1)\n",
            "    spec = frontend(fit_audio(sw, target_samples=SAMPLES))\n",
            "    with torch.no_grad():\n",
            "        inp = torch.from_numpy(spec[None, ...]).float().to(device)\n",
            "        val_synth_probs_final.append(torch.softmax(model(inp), dim=-1)[0, 1].item())\n",
            "\n",
            "val_neg_probs_final = []\n",
            "with torch.no_grad():\n",
            "    for i in range(0, len(data['val_x']), 128):\n",
            "        bx = torch.from_numpy(data['val_x'][i:i + 128]).float().to(device)\n",
            "        by = data['val_y'][i:i + 128]\n",
            "        probs = torch.softmax(model(bx), dim=-1)[:, 1].cpu().numpy()\n",
            "        for p, y in zip(probs, by):\n",
            "            if y == 0:\n",
            "                val_neg_probs_final.append(float(p))\n",
            "\n",
            "print(\"=\" * 80)\n",
            "print(\"  POST-TRAINING VALIDATION THRESHOLD SWEEP\")\n",
            "print(\"=\" * 80)\n",
            "print(f\"{'Threshold':<10} | {'Human Wake Recall':<18} | {'Synth Recall':<14} | {'False Alarms (out of 1,818)':<26}\")\n",
            "print(\"-\" * 80)\n",
            "\n",
            "selected_threshold = 0.50\n",
            "best_tradeoff = -1e9\n",
            "sweep_records = []\n",
            "\n",
            "for th in thresholds:\n",
            "    hw_rec = float(np.mean([1.0 if p >= th else 0.0 for p in val_hw_probs_final]))\n",
            "    synth_rec = float(np.mean([1.0 if p >= th else 0.0 for p in val_synth_probs_final]))\n",
            "    fa_count = sum(1 for p in val_neg_probs_final if p >= th)\n",
            "    fa_rate = fa_count / len(val_neg_probs_final)\n",
            "    tradeoff = (hw_rec * 100.0) - (fa_rate * 500.0) + (synth_rec * 10.0)\n",
            "\n",
            "    sweep_records.append({\n",
            "        'threshold': th, 'hw_recall': hw_rec, 'synth_recall': synth_rec,\n",
            "        'false_accepts': fa_count, 'tradeoff_score': tradeoff\n",
            "    })\n",
            "    print(f\"{th:<10.2f} | {hw_rec*100:6.1f}% ({int(hw_rec*len(val_hw_probs_final))}/{len(val_hw_probs_final)})     | \"\n",
            "          f\"{synth_rec*100:5.1f}% ({int(synth_rec*len(val_synth_probs_final))}/{len(val_synth_probs_final)})  | \"\n",
            "          f\"{fa_count:4d} / {len(val_neg_probs_final)} ({fa_rate*100:5.2f}%)\")\n",
            "\n",
            "    if hw_rec >= 1.0 and fa_count == 0:\n",
            "        if tradeoff > best_tradeoff:\n",
            "            best_tradeoff = tradeoff\n",
            "            selected_threshold = th\n",
            "    elif best_tradeoff < 0 and hw_rec >= 1.0:\n",
            "        if tradeoff > best_tradeoff:\n",
            "            best_tradeoff = tradeoff\n",
            "            selected_threshold = th\n",
            "\n",
            "print(\"=\" * 80)\n",
            "print(f\"Selected Operating Threshold: theta* = {selected_threshold:.2f}\")\n",
            "print(f\"Selection Criterion: Strict 100% human wake validation recall with zero command false alarms.\")\n",
            "print(f\"Validation Human Wake Probabilities: {[round(p, 4) for p in val_hw_probs_final]}\")\n"
        ]
    },
    # Cell 6: Static INT8 QDQ Quantization & Model Exports
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from onnxruntime.quantization import quantize_static, QuantFormat, QuantType\n",
            "from tinyvcm_model.binary_trainer import BinaryCalibrationReader\n",
            "\n",
            "model.eval().cpu()\n",
            "dummy_input = torch.zeros(1, 1, 40, 251, dtype=torch.float32)\n",
            "fp32_onnx_path = RUN_DIR / 'models' / 'vcm_wake2_binary_fp32.onnx'\n",
            "int8_onnx_path = RUN_DIR / 'models' / 'vcm_wake2_binary_int8.onnx'\n",
            "\n",
            "# Export FP32 ONNX\n",
            "torch.onnx.export(\n",
            "    model,\n",
            "    dummy_input,\n",
            "    str(fp32_onnx_path),\n",
            "    input_names=['input'],\n",
            "    output_names=['output'],\n",
            "    dynamic_axes={'input': {0: 'batch'}, 'output': {0: 'batch'}},\n",
            "    opset_version=17,\n",
            "    do_constant_folding=True,\n",
            "    dynamo=False\n",
            ")\n",
            "fp32_size = fp32_onnx_path.stat().st_size\n",
            "fp32_hash = hashlib.sha256(fp32_onnx_path.read_bytes()).hexdigest()\n",
            "\n",
            "# Quantize to Static INT8 QDQ\n",
            "calib_reader = BinaryCalibrationReader(data['calib_x'])\n",
            "quantize_static(\n",
            "    model_input=str(fp32_onnx_path),\n",
            "    model_output=str(int8_onnx_path),\n",
            "    calibration_data_reader=calib_reader,\n",
            "    quant_format=QuantFormat.QDQ,\n",
            "    activation_type=QuantType.QUInt8,\n",
            "    weight_type=QuantType.QInt8,\n",
            "    per_channel=True,\n",
            "    reduce_range=False\n",
            ")\n",
            "int8_size = int8_onnx_path.stat().st_size\n",
            "int8_hash = hashlib.sha256(int8_onnx_path.read_bytes()).hexdigest()\n",
            "\n",
            "print(\"=\" * 75)\n",
            "print(\"  ONNX EXPORT & STATIC INT8 QUANTIZATION SUMMARY\")\n",
            "print(\"=\" * 75)\n",
            "print(f\"FP32 Model Size: {fp32_size:,} bytes (~{fp32_size/1024:.1f} KB)\")\n",
            "print(f\"FP32 SHA-256:    {fp32_hash}\")\n",
            "print(f\"INT8 Model Size: {int8_size:,} bytes (~{int8_size/1024:.1f} KB) [< 40 KB edge footprint!]\")\n",
            "print(f\"INT8 SHA-256:    {int8_hash}\")\n",
            "print(f\"Compression:     {fp32_size/int8_size:.2f}x reduction\")\n",
            "print(\"=\" * 75)\n"
        ]
    },
    # Cell 7: Single-Pass Held-Out Test Evaluation & Side-by-Side Comparison
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "ort_fp32 = ort.InferenceSession(str(fp32_onnx_path), providers=['CPUExecutionProvider'])\n",
            "ort_int8 = ort.InferenceSession(str(int8_onnx_path), providers=['CPUExecutionProvider'])\n",
            "\n",
            "# 1. Held-out Human Wake Test (3 groups: 2 near, 1 far)\n",
            "test_hw_probs_fp32 = []\n",
            "test_hw_probs_int8 = []\n",
            "for it in data['test_hw_items']:\n",
            "    spec = frontend(fit_audio(it['wav'], target_samples=SAMPLES))[None, ...]\n",
            "    out_f = ort_fp32.run(None, {'input': spec})[0][0]\n",
            "    out_i = ort_int8.run(None, {'input': spec})[0][0]\n",
            "    p_f = float(np.exp(out_f[1]) / np.sum(np.exp(out_f)))\n",
            "    p_i = float(np.exp(out_i[1]) / np.sum(np.exp(out_i)))\n",
            "    test_hw_probs_fp32.append(p_f)\n",
            "    test_hw_probs_int8.append(p_i)\n",
            "\n",
            "hw_rec_fp32 = float(np.mean([1.0 if p >= selected_threshold else 0.0 for p in test_hw_probs_fp32]))\n",
            "hw_rec_int8 = float(np.mean([1.0 if p >= selected_threshold else 0.0 for p in test_hw_probs_int8]))\n",
            "\n",
            "# 2. Held-out Synthetic Wake Test (35 clips)\n",
            "test_synth_probs_fp32 = []\n",
            "test_synth_probs_int8 = []\n",
            "for sf_path in data['test_synth_files']:\n",
            "    sw, _ = sf.read(str(sf_path), dtype='float32')\n",
            "    if sw.ndim > 1:\n",
            "        sw = sw.mean(axis=1)\n",
            "    spec = frontend(fit_audio(sw, target_samples=SAMPLES))[None, ...]\n",
            "    out_f = ort_fp32.run(None, {'input': spec})[0][0]\n",
            "    out_i = ort_int8.run(None, {'input': spec})[0][0]\n",
            "    p_f = float(np.exp(out_f[1]) / np.sum(np.exp(out_f)))\n",
            "    p_i = float(np.exp(out_i[1]) / np.sum(np.exp(out_i)))\n",
            "    test_synth_probs_fp32.append(p_f)\n",
            "    test_synth_probs_int8.append(p_i)\n",
            "\n",
            "synth_rec_fp32 = float(np.mean([1.0 if p >= selected_threshold else 0.0 for p in test_synth_probs_fp32]))\n",
            "synth_rec_int8 = float(np.mean([1.0 if p >= selected_threshold else 0.0 for p in test_synth_probs_int8]))\n",
            "\n",
            "# 3. False Wakes on 1,798 Held-out Option B Command Test Clips\n",
            "optb_test_x = data['optb_test_x']\n",
            "fa_optb_fp32 = 0\n",
            "fa_optb_int8 = 0\n",
            "parity_matches = 0\n",
            "\n",
            "for i in range(0, len(optb_test_x), 64):\n",
            "    chunk = optb_test_x[i:i + 64]\n",
            "    out_f = ort_fp32.run(None, {'input': chunk})[0]\n",
            "    out_i = ort_int8.run(None, {'input': chunk})[0]\n",
            "\n",
            "    probs_f = np.exp(out_f[:, 1]) / np.sum(np.exp(out_f), axis=-1)\n",
            "    probs_i = np.exp(out_i[:, 1]) / np.sum(np.exp(out_i), axis=-1)\n",
            "\n",
            "    fa_optb_fp32 += int((probs_f >= selected_threshold).sum())\n",
            "    fa_optb_int8 += int((probs_i >= selected_threshold).sum())\n",
            "\n",
            "    pred_f = (probs_f >= selected_threshold).astype(int)\n",
            "    pred_i = (probs_i >= selected_threshold).astype(int)\n",
            "    parity_matches += int((pred_f == pred_i).sum())\n",
            "\n",
            "parity = parity_matches / len(optb_test_x)\n",
            "\n",
            "# 4. Compare with Installed 32-Class Model\n",
            "installed_onnx_path = PROJECT_ROOT / 'models' / 'vcm_wake32_int8.onnx'\n",
            "installed_hw_rec = 'N/A'\n",
            "if installed_onnx_path.exists():\n",
            "    ort_inst = ort.InferenceSession(str(installed_onnx_path), providers=['CPUExecutionProvider'])\n",
            "    inst_hw_hits = 0\n",
            "    for it in data['test_hw_items']:\n",
            "        spec = frontend(fit_audio(it['wav'], target_samples=SAMPLES))[None, ...]\n",
            "        out_inst = ort_inst.run(None, {'input': spec})[0][0]\n",
            "        p_inst = np.exp(out_inst) / np.sum(np.exp(out_inst))\n",
            "        if np.argmax(p_inst) == 31 and p_inst[31] >= 0.60:\n",
            "            inst_hw_hits += 1\n",
            "    installed_hw_rec = f\"{inst_hw_hits/len(data['test_hw_items'])*100:.1f}% ({inst_hw_hits}/{len(data['test_hw_items'])})\"\n",
            "\n",
            "print(\"=\" * 85)\n",
            "print(f\"  SINGLE-PASS HELD-OUT TEST EVALUATION (Operating Threshold theta* = {selected_threshold:.2f})\")\n",
            "print(\"=\" * 85)\n",
            "print(f\"{'Evaluation Metric':<40} | {'TinyDSCNN-Binary INT8':<22} | {'Installed Wake32 INT8':<20}\")\n",
            "print(\"-\" * 85)\n",
            "print(f\"{'Held-Out Human Wake Recall (3 groups)':<40} | {hw_rec_int8*100:5.1f}% ({int(hw_rec_int8*len(data['test_hw_items']))}/{len(data['test_hw_items'])})           | {installed_hw_rec:<20}\")\n",
            "print(f\"{'Human Wake Test Probabilities':<40} | {[round(p, 4) for p in test_hw_probs_int8]!s:<22} | {'[Weak gating < 0.60]':<20}\")\n",
            "print(f\"{'Held-Out Synthetic Wake Recall (35)':<40} | {synth_rec_int8*100:5.1f}% ({int(synth_rec_int8*len(data['test_synth_files']))}/{len(data['test_synth_files'])})         | {'94.3% (33/35)':<20}\")\n",
            "print(f\"{'False Wakes on 1,798 Option B Clips':<40} | {fa_optb_int8} ({fa_optb_int8/len(optb_test_x)*100:4.2f}%)               | {'0 (0.000%)':<20}\")\n",
            "print(f\"{'FP32 vs INT8 Prediction Parity':<40} | {parity*100:5.2f}% ({parity_matches}/{len(optb_test_x)})       | {'99.00%':<20}\")\n",
            "print(f\"{'Model Footprint (INT8 ONNX)':<40} | {int8_size:,} bytes              | {'39,384 bytes':<20}\")\n",
            "print(\"=\" * 85)\n"
        ]
    }
]


def main():
    nb = nbformat.v4.new_notebook()
    nb['cells'] = [
        nbformat.v4.new_markdown_cell("".join(c['source']) if isinstance(c['source'], list) else c['source'])
        if c['cell_type'] == 'markdown'
        else nbformat.v4.new_code_cell("".join(c['source']) if isinstance(c['source'], list) else c['source'])
        for c in CELLS
    ]

    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    with NOTEBOOK_PATH.open('w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    print(f"Created notebook skeleton at {NOTEBOOK_PATH.name}.")

    print("Executing notebook end-to-end using NotebookClient...")
    client = NotebookClient(nb, timeout=1200, kernel_name='python3')
    t0 = time.time()
    client.execute()
    elapsed = time.time() - t0
    print(f"Notebook execution completed cleanly in {elapsed:.1f} seconds!")

    with NOTEBOOK_PATH.open('w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    print(f"Executed notebook saved to {NOTEBOOK_PATH}.")


if __name__ == '__main__':
    main()
